# config.yaml

# --- 기본 설정 ---
# 영상 폴더 경로
input_folder_path: "INPUT"
# 저장 최상위 폴더 경로
master_output_folder: "EXTRACTED_SLIDES"
# 영상 파일 확장자 (리스트 형식)
video_extensions:
  - .mp4
  - .mov
  - .avi
  - .mkv

# --- 처리 옵션 ---
# 프레임 비교 간격
frame_interval: 30
# 사용할 비교 방식: 'METHOD_PIXEL_DIFF' 또는 'METHOD_SSIM_DIFF'
comparison_method: 'METHOD_SSIM_DIFF'

# --- 각 방식별 임계값 --- (0에 가까울수록 유사)
# 픽셀 차이 임계값
pixel_diff_threshold: 0.01
# SSIM 차이 임계값
ssim_diff_threshold: 0.02